### ISSUE TITLE
nuget reference wrong version in .NET Core

### ISSUE THREAD

**Issue by plindjo** [iNKORE-NET/UI.WPF.Modern#57]
**Describe the bug**
Project references a wrong assembly version (1.2.3.0) when using nuget package v 0.9.27  with .NET Core

**To Reproduce**
1. Create project for .NET6.0 following the [Quick Start](https://github.com/iNKORE-NET/Documentation/blob/main/data/docs/ui.wpf.modern/02.%23%20onboarding/index.en-US.mdx)
2. Build project
3. See errors in designer/xaml or Error List

**Expected behavior**
Expected an application similar to the quick start sample

**Screenshots**
![AssemblyVersion](https://github.com/iNKORE-NET/UI.WPF.Modern/assets/18084211/a1b0846c-247c-4823-a089-0b2a7dd2f3c5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2 (19045.4291)
- Visual Studio Enterprise 2022 (17.9.6)

**Comment by NotYoojun** [comment]
Hi there, this problem has been existing for a while and I have no idea to fix it.
I believe this is caused by the wrong configuration of the nuget package.

You can try add `iNKORE.UI.WPF` in your project, this will fix this error.

If you're good at nuget config files, you can do something to the nuget package and send it back to us.

**Comment by plindjo** [comment]
The issue is resolved with latest version.

**Comment by NotYoojun** [comment]
Glad to hear that. Please dont hesitate to open a new issue if anything happes.
Thanks!
